openapi: 3.0.0
info:
  version: 1.0.0
  title: hubme api
servers:
  - url: http://localhost:8080
paths:
  /user/{uuid}:
    get:
      summary: ユーザー情報取得
      description: ユーザーの情報をuuidで取得
      operationId: UserFindByID
      parameters:
        - $ref: '#/components/parameters/UserUUIDRequest'
      responses:
        '200':
          description: Successfully get user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successful get user by id
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Failed to find user data by uuid
    put:
      summary: ユーザー情報を更新
      description: ユーザー情報をuuidで更新
      operationId: UserFindByID
      parameters:
        - $ref: '#/components/parameters/UserUUIDRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserWithoutPassword'
      responses:
        '200':
          description: Successfully get user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successful get user by id
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Failed to find user data by uuid
  /user/signup:
    post:
      summary: ユーザーのサインアップ
      description: ユーザーのサインアップ
      operationId: SignupUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: サインアップ成功
  /user/signin:
    post:
      summary: ユーザーのサインイン
      description: ユーザーのサインイン
      operationId: SigninUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signin'
      responses:
        '200':
          description: Successfully signin user
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    format: string
                    description: ユーザーのuuid
                    example: ffafafafffafaf
  /community/{uuid}:
    get:
      summary: コミュニティ情報取得
      description: コミュニティ情報をuuidで取得
      operationId: CommunityFindByID
      parameters:
        - $ref: '#/components/parameters/CommunityUUIDRequest'
      responses:
        '200':
          description: Successfully get community data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successful get community by id
                  user:
                    $ref: '#/components/schemas/Community'
        '400':
          description: Failed to find community data by uuid
    put:
      summary: コミュニティ情報を更新
      description: コミュニティ情報をuuidで更新
      operationId: CommunityFindByID
      parameters:
        - $ref: '#/components/parameters/CommunityUUIDRequest'
      responses:
        '200':
          description: Successfully get community data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: successful get community by id
                  user:
                    $ref: '#/components/schemas/Community'
        '400':
          description: Failed to find community data by uuid
  /community/signup:
    post:
      summary: コミュニティのサインアップ
      description: コミュニティのサインアップ
      operationId: SignupCommunity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Community'
      responses:
        '201':
          description: サインアップ成功
  /community/signin:
    post:
      summary: コミュニティのサインイン
      description: コミュニティのサインイン
      operationId: SigninCommunity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signin'
      responses:
        '200':
          description: Successfully signin community
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    format: string
                    description: communityのuuid
                    example: ffafafafffafaf
  /session:
    get:
      summary: セッション
      description: セッション
      operationID: session
      parameters:
        - in: header
          name: session-name
          schema:
            type: string
          required: true
          description: sessionの名前
      responses:
        '200':
          description: 認証成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
  /createEvent:
    post:
      summary: イベント作成
      description: イベント作成
      operationId: CreateEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: イベント作成成功
  /scoutlist/getcommunitydetail:
    get:
      summary: スカウトリストの一覧を取得
      description: statusは 0:未読、1:既読、2：興味なし、3:興味あり、uuidはcommunityのuuidを入れる
      operationId: get_scout_list
      parameters:
        - name: user_uuid
          in: query
          required: true
          description: ユーザーのID
          schema:
            type: string
      responses:
        '200':
          description: スカウトに一覧取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetCommunityScoutDetail'
  /scoutlist/updatestatus:
    put:
      summary: スカウトのステータスを変更
      description: 0:未読、1:既読、2：興味なし、3:興味あり
      operationId: changeScoutStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeScoutStatus'
      responses:
        '200':
          description: イベントのステータス変更成功
components:
  parameters:
    UserUUIDRequest:
      name: uuid
      in: path
      required: true
      description: ユーザーのID
      schema:
        type: string
    CommunityUUIDRequest:
      name: uuid
      in: path
      required: true
      description: コミュニティのID
      schema:
        type: string
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          format: string
          description: ”ユーザーの名前"
          example: やまけん
        email:
          type: string
          format: string
          description: メールアドレス
          example: email
        password:
          type: string
          format: string
          description: パスワード
          example: hogehoge
        img:
          type: string
          format: string
          description: イメージのs3パス
          example: hogehoge.jpeg
        self:
          type: string
          format: string
          description: 自己紹介
          example: hogehoge
        mem1:
          type: string
          format: string
          description: 所属1
          example: A univ.
        mem2:
          type: string
          format: string
          description: 所属２
          example: B Club
        mem3:
          type: string
          format: string
          description: 所属3
          example: ''
      required:
        - uuid
        - name
        - email
        - password
    UserWithoutPassword:
      tupe: object
      properties:
        name:
          type: string
          format: string
          description: ”ユーザーの名前"
          example: やまけん
        email:
          type: string
          format: string
          description: メールアドレス
          example: email
        img:
          type: string
          format: string
          description: イメージのs3パス
          example: hogehoge.jpeg
        self:
          type: string
          format: string
          description: 自己紹介
          example: hogehoge
        mem1:
          type: string
          format: string
          description: 所属1
          example: A univ.
        mem2:
          type: string
          format: string
          description: 所属２
          example: B Club
        mem3:
          type: string
          format: string
          description: 所属3
          example: ''
      required:
        - name
        - email
        - mem1
    Signin:
      type: object
      properties:
        email:
          type: string
          format: string
          description: メールアドレス
          example: email
        password:
          type: string
          format: string
          description: パスワード
          example: hogehoge
      required:
        - email
        - password
    Community:
      type: object
      properties:
        uuid:
          type: string
          format: string
          description: コミュニティのuuid
          example: ffafafafffafaf
        name:
          type: string
          format: string
          description: ”コミュニティ名"
          example: RCC
        email:
          type: string
          format: string
          description: メールアドレス
          example: email
        password:
          type: string
          format: string
          description: パスワード
          example: hogehoge
        img:
          type: string
          format: string
          description: イメージのs3パス
          example: hogehoge.jpeg
        self:
          type: string
          format: string
          description: 自己紹介
          example: hogehoge
        mem1:
          type: string
          format: string
          description: 所属1
          example: A univ.
        mem2:
          type: string
          format: string
          description: 所属２
          example: B Club
        mem3:
          type: string
          format: string
          description: 所属3
          example: ''
      required:
        - uuid
        - name
        - email
        - password
    Session:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: アカウントのuuid
          example: hoge
        account_type:
          type: string
          format: string
          description: アカウントタイプ
          example: user
        status:
          type: string
          format: string
          description: 承認済みかのステータス
          example: authenticated
      required:
        - uuid
        - account_type
        - status
    Event:
      type: object
      properties:
        community_uuid:
          type: string
          format: string
          description: コミュニティのuuid
          example: lksahkhakhkfahkl
        title:
          type: string
          format: string
          description: イベントタイトル
          exmple: 学祭
        img:
          type: string
          format: string
          description: イベント画像
          example: /hogehoge.ping
        detailed:
          type: string
          format: string
          description: RCC学祭について...
          date: 11月10日
          tag:
            - 1
            - 2
      required:
        - community_uuid
        - title
        - img
        - detailed
    GetCommunityScoutDetail:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: チャットルームID
          example: 1
        status:
          type: integer
          format: int32
          description: スカウトステータス（0:未承認、1:承認保留、2:承認破棄、3:承認）
          example: 0
        unread_count:
          type: integer
          format: int32
          description: メッセージの未読件数
          example: 0
        uuid:
          type: string
          description: コミュニティのUUID
          example: community_uuid
        detail_info:
          type: object
          properties:
            name:
              type: string
              description: 名前
              example: name
            img:
              type: string
              format: string
              description: 画像URL
              example: image_url
            mem1:
              type: string
              format: string
              description: 所属1
              example: 立命館
            tags:
              type: array
              items:
                type: string
              example:
                - tag1
                - tag2
                - tag3
          required:
            - name
            - img
            - mem1
            - tags
      required:
        - id
        - status
        - unread_count
        - uuid
        - detail_info
    ChangeScoutStatus:
      type: object
      properties:
        user_uuid:
          type: string
          format: uuid
          description: userのuuid
          example: 123e4567-e89b-12d3-a456-426614174000
        status:
          type: int
          format: uint
          description: スカウトのステータス(0:未読、1:既読、2：興味なし、3:興味あり)
          example: 1
      required:
        - user_uuid
        - status
