services:
  app:
    container_name: app
    build:
      context: .
      target: builder
    volumes:
      - ./:/project/
    working_dir: /project
    tty: true
    ports:
      - 8080:80
    command: sh -c 'go mod tidy && air'